### ISSUE TITLE
New PyPi package version with latest

### ISSUE THREAD

**Issue by ahmetb** [aouyar/healthgraph-api#7]
I really appreciate if you can find time to push a new version on pypi.

**Comment by aouyar** [comment]
I will be pushing a new version on PyPi this weekend.

**Comment by ahmetb** [comment]
Any updates?

**Comment by ahmetb** [comment]
Hi, people still are using this library. Please consider updating this.

**Comment by ahmetb** [comment]
duplicate of #10.

**Comment by CNG** [comment]
Happy to carry on the annual ping
